"""Mock research briefs for the Phase 2 voice test.

30 briefs — 10 per format — spread across all six content wells. These stand in
for the (not-yet-built) research layer so we can stress-test generation voice
and the compliance gate before wiring anything upstream. Supporting facts are
intentionally general and brand-safe; this exercises voice, not fact-checking.
"""
from __future__ import annotations

from schemas import ResearchBrief, SupportingFact


def _brief(well, title, summary, fact, url, source, fmt, notes, list_count=None, evergreen=True):
    return ResearchBrief(
        well_id=well,
        angle_title=title,
        angle_summary=summary,
        supporting_facts=[SupportingFact(fact=fact, source_url=url, source_name=source)],
        suggested_format=fmt,
        suggested_list_count=list_count,
        evergreen=evergreen,
        voice_compatibility_notes=notes,
    )


# --------------------------------------------------------------------------
# 10 QUOTE briefs
# --------------------------------------------------------------------------
_QUOTE = [
    _brief("wealth_psychology",
           "Contentment is a skill, not a balance",
           "The capacity to feel 'enough' is learned, and it does more for financial peace than any raise.",
           "Studies on the hedonic treadmill show people quickly adapt to higher incomes and return to a baseline level of satisfaction.",
           "https://www.apa.org/topics/money/income-happiness", "American Psychological Association",
           "quote", "Frame contentment as a practiced skill, not deprivation. No advice."),
    _brief("long_game",
           "Patience is the cheapest investment with the highest cost to skip",
           "Time in the market and consistency beat timing; the hard part is temperament, not math.",
           "Long-run studies of consistent contributors show most underperformance comes from interrupting a plan, not from poor selection.",
           "https://www.morningstar.com/lp/mind-the-gap", "Morningstar",
           "quote", "Anchor in patience and staying the course. No tickers, no asset names."),
    _brief("common_mistakes",
           "Lifestyle inflation is the silent tax on every raise",
           "Spending rises to meet income unless a deliberate anchor is set.",
           "Behavioral research finds spending tends to rise with income unless savings increases are automated first.",
           "https://www.consumerfinance.gov", "Consumer Financial Protection Bureau",
           "quote", "Stoic framing of 'enough'. Educational, not prescriptive."),
    _brief("stoic_money",
           "We do not control the price; we control the contribution",
           "The Stoic dichotomy of control maps cleanly onto investing behavior.",
           "Epictetus distinguished between what is up to us and what is not — a framing widely applied to managing financial anxiety.",
           "https://plato.stanford.edu/entries/epictetus/", "Stanford Encyclopedia of Philosophy",
           "quote", "Paraphrase Epictetus only — no fabricated quote marks. Use 'investments' generically."),
    _brief("daily_discipline",
           "Automation turns willpower into a one-time decision",
           "Automating savings removes the daily friction of choosing to save.",
           "Default-enrollment retirement plans dramatically raise participation versus opt-in, showing the power of defaults.",
           "https://www.nber.org/papers/w7682", "National Bureau of Economic Research",
           "quote", "Celebrate defaults and automation. No product names."),
    _brief("frugal_frameworks",
           "Enough is a number you set, not one you reach",
           "Without a chosen anchor, 'enough' drifts upward forever.",
           "Surveys repeatedly find that the income people say they need rises in proportion to the income they already have.",
           "https://news.gallup.com", "Gallup",
           "quote", "Frame 'enough' as a deliberate choice. Stoic-flavored."),
    _brief("wealth_psychology",
           "Comparison spends money you never agreed to spend",
           "Social comparison silently drives purchases that wouldn't happen in isolation.",
           "Research links social media use to increased spending and lower financial satisfaction through comparison effects.",
           "https://www.jstor.org", "Journal of Consumer Research",
           "quote", "Anti-comparison angle. Specific scene encouraged. No hype."),
    _brief("long_game",
           "Boring, repeated, and undisturbed beats clever almost every time",
           "Consistency compounds; cleverness usually interrupts the compounding.",
           "Index of consistent long-term savers shows steady contribution outperforms frequent strategy changes over decades.",
           "https://www.dalbar.com", "DALBAR",
           "quote", "Praise boring consistency. No specific funds or returns promised."),
    _brief("stoic_money",
           "Wanting less is its own kind of wealth",
           "Seneca's idea that no one is poor who has enough, reframed for modern spending.",
           "Seneca argued in his letters that poverty is a matter of desire, not of possessions.",
           "https://www.gutenberg.org/ebooks/56075", "Seneca, Letters from a Stoic",
           "quote", "Paraphrase Seneca in your own words. Never invent a direct quotation."),
    _brief("daily_discipline",
           "The pause before a purchase is where most savings live",
           "A short waiting period filters out most impulse buys at no cost.",
           "Studies of cooling-off periods show a majority of impulse purchase urges fade within a day.",
           "https://www.sciencedirect.com", "Journal of Consumer Psychology",
           "quote", "Concrete: name the pause. Calm, not preachy."),
]

# --------------------------------------------------------------------------
# 10 MINI-BLOG briefs
# --------------------------------------------------------------------------
_MINIBLOG = [
    _brief("common_mistakes",
           "Why sunk costs quietly steer everyday spending",
           "People keep spending to justify past spending; naming the bias loosens its grip.",
           "The sunk-cost fallacy leads people to continue investing in a losing course of action because of resources already committed.",
           "https://www.behavioraleconomics.com", "Behavioral Economics Guide",
           "mini_blog", "Concrete domestic example (a gym membership, a subscription). Educational."),
    _brief("long_game",
           "What a small, steady monthly habit becomes over decades",
           "Compound growth rewards consistency more than size; illustrate with general numbers.",
           "At a 7% average annual return, modest monthly contributions can grow into substantial sums over 30 years through compounding.",
           "https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator", "Investor.gov",
           "mini_blog", "Educational compound illustration is fine; never promise the reader an outcome."),
    _brief("wealth_psychology",
           "The treadmill that turns every raise into a new normal",
           "Hedonic adaptation resets satisfaction after each upgrade.",
           "Hedonic adaptation describes how people return to a stable baseline of happiness after positive or negative changes, including income.",
           "https://www.apa.org", "American Psychological Association",
           "mini_blog", "Stoic angle on contentment. One vivid scene of a raise disappearing."),
    _brief("stoic_money",
           "Seneca's quiet argument against the fear of losing money",
           "Practicing imagined loss reduces its power — a Stoic exercise applied to finances.",
           "Seneca recommended periodically imagining the loss of comforts to reduce anxiety about losing them.",
           "https://www.gutenberg.org/ebooks/56075", "Seneca, Letters from a Stoic",
           "mini_blog", "Paraphrase only. Connect negative visualization to financial calm."),
    _brief("daily_discipline",
           "The quiet power of deciding once instead of every day",
           "Defaults remove decision fatigue and protect good habits.",
           "Decision fatigue research shows the quality of choices degrades over a day of repeated decisions.",
           "https://www.pnas.org", "Proceedings of the National Academy of Sciences",
           "mini_blog", "Frame automation as buying back attention. Concrete examples."),
    _brief("frugal_frameworks",
           "Why a 24-hour wait does most of a budget's work for free",
           "A cooling-off rule filters impulse spending without tracking every dollar.",
           "Impulse buying accounts for a large share of discretionary spending and tends to fade with a short delay.",
           "https://www.sciencedirect.com", "Journal of Consumer Psychology",
           "mini_blog", "Practical and calm. No 'hack' language."),
    _brief("common_mistakes",
           "What loss aversion does to people during a market dip",
           "Losses feel larger than equivalent gains, which drives panic selling.",
           "Kahneman and Tversky's prospect theory found losses are psychologically about twice as powerful as equivalent gains.",
           "https://www.nobelprize.org/prizes/economic-sciences/2002/kahneman/facts/", "The Nobel Prize",
           "mini_blog", "Explain the bias; never tell the reader to buy, sell, or hold."),
    _brief("wealth_psychology",
           "Comparison is the line item that never shows on a statement",
           "Comparison shapes spending invisibly; awareness is the lever.",
           "Frequent social comparison is associated with lower financial satisfaction independent of actual income.",
           "https://www.jstor.org", "Journal of Consumer Research",
           "mini_blog", "Anti-comparison. End with a specific, answerable question."),
    _brief("long_game",
           "Time in the market versus the urge to time the market",
           "Missing a handful of best days erases much of a long-run return.",
           "Analyses repeatedly show that missing the market's best days substantially lowers long-term returns for those who try to time it.",
           "https://www.morningstar.com", "Morningstar",
           "mini_blog", "Educational, no advice. Emphasize temperament over tactics."),
    _brief("stoic_money",
           "Applying the dichotomy of control to a falling market",
           "Separate the controllable contribution from the uncontrollable price.",
           "The Stoic dichotomy of control is widely used in modern cognitive approaches to anxiety, including financial anxiety.",
           "https://plato.stanford.edu/entries/epictetus/", "Stanford Encyclopedia of Philosophy",
           "mini_blog", "Paraphrase Epictetus. Calm, never alarmist about markets."),
]

# --------------------------------------------------------------------------
# 10 LIST briefs (mix of 5 and 10)
# --------------------------------------------------------------------------
_LIST = [
    _brief("daily_discipline",
           "10 quiet money habits that compound over a lifetime",
           "Small, repeatable disciplines that grow more powerful the longer they are kept.",
           "Automating savings and reviewing subscriptions regularly are among the habits most associated with long-term financial stability.",
           "https://www.consumerfinance.gov", "Consumer Financial Protection Bureau",
           "list", "Each item concrete and non-prescriptive. No products.", list_count=10),
    _brief("common_mistakes",
           "5 things financially calm people quietly stop doing",
           "Removing a few stressful patterns matters more than adding new tactics.",
           "Frequent account-checking and comparison-driven spending are common patterns linked to financial stress.",
           "https://www.apa.org", "American Psychological Association",
           "list", "Calm, anti-comparison. Each item earns its place.", list_count=5),
    _brief("frugal_frameworks",
           "5 budgeting frameworks worth understanding before you pick one",
           "A short tour of well-known frameworks so a reader can choose calmly.",
           "Common frameworks include 50/30/20, zero-based budgeting, envelope systems, pay-yourself-first, and no-spend periods.",
           "https://www.investor.gov", "Investor.gov",
           "list", "Describe frameworks neutrally; do not tell the reader which to use.", list_count=5),
    _brief("wealth_psychology",
           "10 questions to ask yourself before a big purchase",
           "A calm checklist that surfaces whether a purchase fits your life.",
           "Reflection and short delays before large purchases are associated with fewer regretted buys.",
           "https://www.sciencedirect.com", "Journal of Consumer Psychology",
           "list", "Questions, not commands. Specific and picture-able.", list_count=10),
    _brief("long_game",
           "5 quiet truths about how compound growth actually works",
           "Plain-language truths about patience and time, no math jargon.",
           "Compounding means earnings themselves begin to earn, which is why early and consistent contributions matter most.",
           "https://www.investor.gov", "Investor.gov",
           "list", "Educational illustrations only; no promised returns.", list_count=5),
    _brief("daily_discipline",
           "10 small frugal rituals that never feel like sacrifice",
           "Gentle defaults that save money without a feeling of deprivation.",
           "Habit research shows small frictionless routines persist far longer than effortful ones.",
           "https://www.pnas.org", "Proceedings of the National Academy of Sciences",
           "list", "Wholesome and specific. Nothing extreme or austere.", list_count=10),
    _brief("common_mistakes",
           "5 ways lifestyle creep sneaks past you",
           "The small upgrades that quietly become the new baseline.",
           "Lifestyle inflation often arrives through small recurring upgrades rather than single large purchases.",
           "https://www.consumerfinance.gov", "Consumer Financial Protection Bureau",
           "list", "Name the small upgrades concretely. No shaming.", list_count=5),
    _brief("stoic_money",
           "5 Stoic ideas for a calmer relationship with money",
           "Ancient practices, paraphrased, that reduce financial anxiety.",
           "Stoic practices like negative visualization and the dichotomy of control are used in modern anxiety management.",
           "https://plato.stanford.edu/entries/stoicism/", "Stanford Encyclopedia of Philosophy",
           "list", "Paraphrase ideas; never fabricate quotations or attribute invented lines.", list_count=5),
    _brief("frugal_frameworks",
           "10 no-spend day ideas that still feel like a good day",
           "Ways to enjoy a day without spending, framed positively.",
           "No-spend challenges help people identify which discretionary purchases they don't actually miss.",
           "https://www.consumerfinance.gov", "Consumer Financial Protection Bureau",
           "list", "Wholesome, family-safe activities. Concrete and warm.", list_count=10),
    _brief("wealth_psychology",
           "5 signs you've quietly made peace with money",
           "Gentle markers of financial calm that have nothing to do with the balance.",
           "Financial well-being research distinguishes subjective financial calm from absolute income or wealth.",
           "https://www.consumerfinance.gov", "Consumer Financial Protection Bureau",
           "list", "Reflective and calm. Signs, not instructions.", list_count=5),
]

ALL_BRIEFS = _QUOTE + _MINIBLOG + _LIST


def all_briefs() -> list[ResearchBrief]:
    return list(ALL_BRIEFS)
